config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'restaurants#index'

  resources :restaurants do
    resources :reviews
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  validates :name, presence: :true, format: { with: /\A[A-Z]/ }

	validates :address, presence: :true, length: { minimum: 3 }

	has_many :reviews

	def average_rating
		if reviews.any?
			# reviews.inject(0) { |total, review|
				# total + review.rating } / reviews.count.to_f
			reviews.average(:rating)
        else
        	'N/A'
        end

	end

end

app/models/review.rb
 class Review < ActiveRecord::Base

 	belongs_to :restaurant
 	validates  :rating, inclusion: { in: 1..5 }
 	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

before_action :authenticate_user!, except: [:index]
	def index

		@restaurants = Restaurant.all
		@review = Review.new
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = Restaurant.create(params[:restaurant].permit(:name, :address, :cuisine))
		if @restaurant.save
			redirect_to '/restaurants'
		else
			render 'new'
		end
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	def destroy
		@restaurant = Restaurant.find(params[:id])
		@restaurant.destroy
		flash[:notice] = 'Baleeted!'
		redirect_to '/restaurants'
	end

	def update
		@restaurant = Restaurant.find(params[:id])
		if @restaurant.update(params[:restaurant].permit(:name, :address, :cuisine))
			redirect_to '/restaurants'
		else
			render 'edit'
		end
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

def new
	@restaurant = Restaurant.find(params[:restaurant_id])
	@review = Review.new
end

def create

	@restaurant = Restaurant.find(params[:restaurant_id])
	@review = @restaurant.reviews.create!(params[:review].permit(:review, :rating))
	# redirect_to '/restaurants'
	render 'create', content_type: :json 
	# (delete line 12. replace with ^^)

	# respond_to do |format|
	# 	format.html{ redirect_to '/restaurants' }
	# 	format.json{ render json: review }
	# end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper

	def star_rating(value)
		return value unless value.respond_to?(:round)

		black_star = value.round
		white_star = 5 - value.round

		return ( '✦' * black_star ) + ( '✧' * white_star)
	end

	def percent_rating(value)
		return value unless value.respond_to?(:round)

		return value * 20
	end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= alert %>
<%= notice %>
<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, required: true %>

	<%= f.label :address %>
	<%= f.text_area :address, required: true %>

	<%= f.label :cuisine %>
	<%= f.text_field :cuisine, required: true %>

	<%= f.submit %>
<% end %>

<% if @restaurant.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>
 
    <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/restaurants/_newreview.html.erb
<%= form_for [restaurant, @review] do |f| %>
	<%= f.label :review %>
	<%= f.text_area :review %>

	<%= f.label :rating %>
	<%= f.select :rating, 1..5 %>

	<%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<template id="review_template">
	<div class='review'>
		{{ review }}
		{{ star_rating }}
	</div>
</template>

<header>

	<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>

	<h1>Kelp.com</h1>
</header>

<div id="main">
<div id="left">
	<% if @restaurants.all.any? %>
		<% @restaurants.all.each do |restaurant| %>
			<div class="restaurant">
				<h4><%= restaurant.name %></h4>
	
				<ul>
					<li>Cuisine: <%= restaurant.cuisine %></li>
					<li>Address: <%= restaurant.address %></li>
					<li>Has <%= pluralize restaurant.reviews.count, 'review' %>
				</ul>

				 Average rating: <%= number_with_precision(percent_rating(restaurant.average_rating), precision: 1) %>%</li>

				<li>Reviews:</li>
				
				<div class='reviews'>
					<% restaurant.reviews.each do |x| %>
						<div class='review'>
							<%= x.review %>
							Rating: <%= star_rating(x.rating) %>
						</div>
					<% end %>
				</div>


				<div class="newreview">
					<%= render 'newreview', restaurant: restaurant %>
				</div>

				<div class="buttons">
					<div class="button">
						<%= link_to "Edit #{restaurant.name}", 	edit_restaurant_path(	restaurant) %>
					</div>
		
					<div class="button">
						<%= link_to "Delete #{restaurant.name}", 	restaurant_path(	restaurant), method: :delete, data: {confirm: 'Can you live with this?'} %>
					</div>

					<div class="extraSpace"></div>
				</div>

			</div>
		<% end %>
	<% else %>
		<h2>Lol no food 4 u!</h2>
	<% end %>

	<input class="button" type="submit" value="Add New Restaurant" 
    onclick="window.location='/restaurants/new';" />
</div>

<div id="right">
</div>
</div>

app/views/restaurants/new.html.erb
<%= form_for @restaurant do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :address %>
	<%= f.text_area :address %>

	<%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
	<%= f.label :review %>
	<%= f.text_area :review %>

	<%= f.label :rating %>
	<%= f.select :rating, 1..5 %>

	<%= f.submit %>
<% end %>